name: Create Release and Upload Assets

on:
  push:
    tags:
      - 'v*'

jobs:
  build-tdl-binaries:
    name: Build tdl binaries
    runs-on: ubuntu-latest
    env:
      DISTPATH: tdl-linux-amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          uv sync
          uv run python gen_filter_cache.py

      - name: Install pyinstaller
        run: uv pip install --system pyinstaller==6.7.0

      - name: Build with PyInstaller
        run: |
          pyinstaller --distpath ./${{ env.DISTPATH }} media_downloader.spec

      - name: Add license and readme
        run: mv README_CN.md README.md ./${{ env.DISTPATH }}

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DISTPATH }}
          path: ${{ env.DISTPATH }}

  create_release:
    name: Create GitHub release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-tdl-binaries
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        shell: bash

  upload_assets:
    name: Upload release assets
    if: startsWith(github.ref, 'refs/tags/')
    needs: create_release
    runs-on: ubuntu-latest
    env:
      DISTPATH: tdl-${{ needs.create_release.outputs.VERSION }}-linux-amd64
    steps:
      - name: Download built binaries
        uses: actions/download-artifact@v4

      - name: Rename and package binaries
        run: |
          zip -r ${{ env.DISTPATH }}.zip ./tdl-linux-amd64/*

      - name: Upload release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: "${{ env.DISTPATH }}.zip"
          asset_name: "${{ env.DISTPATH }}.zip"
          asset_content_type: application/zip
